version: '3'
services:
  book-logstash:
    image: santosr09/book-logstash
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=loma1234
      - MYSQL_DATABSE=test_books
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=loma1234
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local
  logstash-data:
    driver: local
networks:
  default:
    external: true
    name: config-server_default
