version: '3'
services:
  book-service:
    image: santosr09/book-service
    ports:
      - 8088:8088
    environment:
      - spring.profiles.active=production
      - spring.cloud.config.uri=http://ec2-3-19-56-102.us-east-2.compute.amazonaws.com:8888
    volumes:
      - api-logs:/api-logs
  book-user-service:
    image: santosr09/book-user-service
    ports:
      - 8089:8089
    environment:
      - spring.application.name=book-user-service
      - spring.profiles.active=production
      - spring.cloud.config.uri=http://ec2-3-19-56-102.us-east-2.compute.amazonaws.com:8888
      - spring.zipkin.baseUrl=http://zipkin:9411
    volumes:
      - api-logs:/api-logs
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
volumes:
  api-logs:
    driver: local
